#!/bin/sh

set -e

if [[ -z `which terraform` ]]; then
  echo 'Error: Install terraform before running this script'
  exit 1
fi

if [[ -z `which aws` ]]; then
  echo 'Error: Install the AWS SDK before running this script'
  exit 1
fi

if [[ -z `terraform version | grep v0.10` ]]; then
  echo 'Error: This script should only be run with terraform v0.10'
  exit 1
fi

function usage() {
  echo 'Usage:\n\t ./tf <COMMAND> [<MODULE>]'
  echo
  echo 'COMMAND: Either `plan` or `apply`'
  echo 'MODULE: Either `base`, `apps`, `seeder`, or omit to do both `base` and `apps`'
  echo
  echo 'Examples:'
  echo '\t./tf plan base'
  echo '\t./tf apply'
  echo '\t./tf apply seeder'
  exit 1
}

BASE="--target module.base"
APPS="--target module.apps"
CORE="--target module.apps.module.core_app --target module.apps.random_id.session_secret"
MAILER="--target module.apps.module.mailer_app --target module.apps.aws_iam_user_policy.mailer_send_ses_email"
GROUP_MAILER="--target module.apps.module.group_mailer_app"
SEED="--target module.seeder"

case "$1 $2" in
  "plan ")
    set -x
    eval terraform plan
    ;;
  "plan base")
    set -x
    eval terraform plan "$BASE"
    ;;
  "plan apps")
    set -x
    eval terraform plan "$APPS"
    ;;
  "plan seeder")
    set -x
    eval terraform plan "$SEED"
    ;;

  "apply ")
    set -x
    eval terraform apply "$BASE"
    eval terraform apply "$CORE"
    eval terraform apply "$MAILER"
    eval terraform apply "$GROUP_MAILER"
    ;;
  "apply base")
    set -x
    eval terraform apply "$BASE"
    ;;
  "apply apps")
    set -x
    eval terraform apply "$CORE"
    eval terraform apply "$MAILER"
    eval terraform apply "$GROUP_MAILER"
    ;;
  "apply seeder")
    set -x
    eval terraform apply "$SEED"
    ;;
  *)
    usage
esac
