#!/bin/sh

set -e
set -o pipefail

if [[ -z `which terraform` ]]; then
  echo 'Error: Install terraform before running this script'
  exit 1
fi

if [[ -z `which aws` ]]; then
  echo 'Error: Install the AWS SDK before running this script'
  exit 1
fi

if [[ -z `terraform version | grep v0.10` ]]; then
  echo 'Error: This script should only be run with terraform v0.10'
  exit 1
fi

function usage() {
  echo 'Usage:\n\t ./tf <COMMAND> [<MODULE>]'
  echo
  echo 'COMMAND: Either `plan` or `apply`'
  echo 'MODULE: Either `base`, `apps`, `seeder`, or omit to do both `base` and `apps`'
  echo
  echo 'Examples:'
  echo '\t./tf plan base'
  echo '\t./tf apply'
  echo '\t./tf apply seeder'
  exit 1
}

BASE="--target module.base"
APPS="--target module.apps"
SEED="--target module.seeder"

function run_terraform() {
  # The sed command is to hide RSA keys/certs from stdout
  eval terraform $@ | sed '/-----BEGIN/,/-----END/d'
}

case "$1 $2" in
  "plan ")
  run_terraform plan "$BASE" "$APPS"
    ;;
  "plan base")
    run_terraform plan "$BASE"
    ;;
  "plan apps")
    run_terraform plan "$APPS"
    ;;
  "plan seeder")
    run_terraform plan "$SEED"
    ;;

  "apply ")
    run_terraform apply "$BASE" "$APPS"
    ;;
  "apply base")
    run_terraform apply "$BASE"
    ;;
  "apply apps")
    run_terraform apply "$APPS"
    ;;
  "apply seeder")
    run_terraform apply "$SEED"
    ;;
  *)
    usage
esac
